CREATE TABLE R(
    A INTEGER,
    B INTEGER);
    

INSERT INTO R VALUES (10,15);
INSERT INTO R VALUES (20,30);
INSERT INTO R VALUES (20,21);
INSERT INTO R VALUES (20,30);
INSERT INTO R VALUES (35,40);

CREATE TABLE S(
    B INTEGER, 
    C INTEGER);


INSERT INTO S VALUES (10,15);
INSERT INTO S VALUES (20,40);
INSERT INTO S VALUES (21,50);
INSERT INTO S VALUES (30,40);
INSERT INTO S VALUES (10,20);
INSERT INTO S VALUES (35,40);



SELECT B + C FROM S WHERE B > 15;


SELECT A, B FROM R ORDER BY B DESC, A DESC;


SELECT DISTINCT A, B FROM R;


SELECT A, SUM(B) FROM R GROUP BY A;


SELECT R.A, MAX(S.C) FROM R JOIN S ON R.B = S.B GROUP BY R.A;


SELECT * FROM R LEFT OUTER JOIN S ON R.B = S.B;


SELECT * FROM S LEFT OUTER JOIN R ON S.B = R.B;


SELECT * FROM R LEFT OUTER JOIN S ON R.B = S.B WHERE R.B < S.B;



DROP TABLE R;
DROP TABLE s;